version: '3'
services:
  hugo:
    container_name: hugo
    build:
      context: hugo
    expose:
      - "80"
    volumes:
      - hugo:/site
      - /etc/localtime:/etc/localtime:ro
    networks:
      - haproxy
    environment:
      BASEURL: $BASEURL

volumes:
  hugo:
    external: true

networks:
  haproxy:
    external:
      name: haproxy
