version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    container_name: kibana
    restart: unless-stopped
    volumes:
      - kibana:/usr/share/kibana/config
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "5601"
    networks:
      - elkstack
      - haproxy
    depends_on:
      - elasticsearch
    environment:
      XPACK_SECURITY_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
      SERVERNAME: $SERVERNAME
      ELASTICSEARCH_USERNAME: $ELASTICSEARCH_USERNAME
      ELASTICSEARCH_PASSWORD: $ELASTICSEARCH_PASSWORD

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: elasticsearch
    restart: unless-stopped
    expose:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch:/usr/share/elasticsearch/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - elkstack
      
  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.2
    container_name: logstash
    restart: unless-stopped
    expose:
      - "9200"
      - "9300"
    volumes:
      - logstashpipeline:/usr/share/logstash/pipeline:rw
      - logstashconfig:/usr/share/logstash/config:rw
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
    networks:
      - elkstack
    depends_on:
      - elasticsearch

volumes:
  kibana:
    external: true
  elasticsearch:
    external: true
  logstashpipeline:
    external: true
  logstashconfig:
    external: true
      
networks:
  elkstack:
    external:
      name: elkstack
  haproxy:
    external:
      name: haproxy
