version: '3'
services:
  flask:
    container_name: flask
    build: flask
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./flask/code/:/code
    networks:
      - haproxy
    expose:
      - "5000"
    environment:
      FLASK_APP: /code/main.py
     # FLASK_DEBUG: 1

networks:
  haproxy:
    external:
      name: haproxy