version: '3'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    expose:
      - "3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_INSTALL_PLUGINS: $GF_INSTALL_PLUGINS
      GF_AUTH_ANONYMOUS_ENABLED: $GF_AUTH_ANONYMOUS_ENABLED