version: '3'
services:
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    expose:
      - "3000"
    volumes:
      - grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_INSTALL_PLUGINS: $GF_INSTALL_PLUGINS
      GF_AUTH_ANONYMOUS_ENABLED: $GF_AUTH_ANONYMOUS_ENABLED
    networks:
      - influxdb

volumes:
  grafana:
    external: true

networks:
  influxdb:
    external:
      name: influxdb
