version: '3'
services:
  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    build:
      context: ./pgadmin
      args:
        public_url: $public_url
        PGADMIN_SETUP_EMAIL: ${PGADMIN_SETUP_EMAIL}
        PGADMIN_SETUP_PASSWORD: ${PGADMIN_SETUP_PASSWORD}
        PGADMIN_VERSION_MAJOR: 1
        PGADMIN_VERSION_MINOR: 6
    expose:
      - "5050"
    networks:
      - haproxy
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin4
      - /etc/localtime:/etc/localtime:ro

networks:
  haproxy:
    external:
      name: haproxy
  postgres:
    external:
      name: postgres

volumes:
  pgadmin:
    external: true
