version: "3"
services:
  jupyter:
    restart: unless-stopped
    build:
      context: jupyter
    container_name: jupyter
    expose:
      - 8888
    volumes:
      - jupyter:/jupyter
    networks:
      - haproxy

volumes:
  jupyter:
    external: true

networks:
  haproxy:
    external:
      name: haproxy
