version: "3"
services:
  jupyter:
    restart: unless-stopped
    build:
      context: jupyter
      args:
        PERSONAL_PIP_PACKAGES: $PERSONAL_PIP_PACKAGES
    container_name: jupyter
    expose:
      - 8888
    volumes:
      - jupyter:/home/jupyter/notebooks
      - /etc/localtime:/etc/localtime:ro
    networks:
      - haproxy

  jupyter-kg:
    restart: unless-stopped
    build:
      context: jupyter
      dockerfile: Dockerfile-kg
      args:
        KG_PERSONAL_PIP_PACKAGES: $KG_PERSONAL_PIP_PACKAGES
    container_name: jupyter-kg
    expose:
      - 8888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - haproxy
    environment:
      KG_AUTH_TOKEN: $KG_AUTH_TOKEN

volumes:
  jupyter:
    external: true

networks:
  haproxy:
    external:
      name: haproxy
