version: "3"
services:
  mongodb:
    restart: unless-stopped
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mongodb
      
volumes:
  mongodb:
    external: true
      
networks:
  mongodb:
    external:
      name: mongodb