version: '3'
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:
    expose:
      - "80"
    volumes:
      - ./config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - haproxy
      - mariadb

networks:
  haproxy:
    external:
      name: haproxy
  mariadb:
    external:
      name: mariadb
