version: '3'
services:
  haproxy:
    container_name: haproxy
    reboot: unless-stopped
    image: haproxy:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - haproxy:/usr/local/etc/haproxy
      - letsencrypt:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - haproxy

volumes:
  haproxy:
    external: true
  letsencrypt:
    external: true

networks:
  haproxy:
    external:
      name: haproxy
