version: '3'
services:
  firefox-sync:
    container_name: firefox-sync
    build:
      context: ./firefox-sync
      args:
        public_url: $public_url
        sqluri: $sqluri
        secret: $secret
        allow_new_users: $allow_new_users
        force_wsgi_environ: $force_wsgi_environ
    expose:
      - "5000"
    networks:
      - haproxy
      - postgres

networks:
  haproxy:
    external:
      name: haproxy
  postgres:
    external:
      name: postgres
