version: '3'
services:
  mariadb:
    container_name: mariadb
    reboot: unless-stopped
    image: mariadb
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mariadb

volumes:
  mariadb:
    external: true

networks:
  mariadb:
    external:
      name: mariadb
