version: '3'

services:
  kali-linux:
    container_name: kali-linux
    build:
      context: kali-linux
    volumes:
      - kali-linux:/home/root
    expose:
      - "22"
      
volumes:
  kali-linux:
    external: true