version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

    networks:
      - postgres
      - haproxy

volumes:
  postgres:
    external: true

networks:
  postgres:
    external:
      name: postgres
  haproxy:
    external:
      name: haproxy