version: '3'
services:
  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    expose:
      - "8086"
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - influxdb

volumes:
  influxdb:
    external: true

networks:
  influxdb:
    external:
      name: influxdb
